# This action is used for communication between the head behavior and  the visual compass package.
# While game initiating the head behavior tells the compass when to take frames from camera stream as ground truth.
# Between adjusting the head orientation should be a fixed time interval (i.e. 0.5 sec),
# to guarantee a still camera and to ensure that the visual compass has finished processing the image frame. # TODO is this necessary? wait for response of compass?

# In binary mode this should be published while the camera is initially pointed at the opponents goal line, then to the own goal line.
# In multiple mode a 360° field of view is needed. Therefore initially the head should be pointed at the opponents goal line,
# then a series of triggering the visual compass and adjusting the head position by an offset starts.

# TODO update docs

# goal definition

std_msgs/Header header

---

# result definition

bool success

---

# feedback

# no feedback needed